export const actionCategories = [
  "all",
  "Video",
  "Music",
  "Social",
  "Creative",
  "Gaming",
  "Messaging",
  "Other",
] as const;

export type ActionCategory = (typeof actionCategories)[number];

// Categories describe the main user intent of a platform, not its technical API.
export const platformCategories: Record<string, Exclude<ActionCategory, "all">> = {
  youtube: "Video",
  twitter: "Social",
  instagram: "Social",
  tiktok: "Video",
  facebook: "Social",
  discord: "Messaging",
  telegram: "Messaging",
  spotify: "Music",
  twitch: "Video",
  vimeo: "Video",
  threads: "Social",
  linkedin: "Social",
  pinterest: "Creative",
  snapchat: "Social",
  reddit: "Social",
  whatsapp: "Messaging",
  bluesky: "Social",
  soundcloud: "Music",
  deezer: "Music",
  kick: "Video",
  rumble: "Video",
  roblox: "Gaming",
  steam: "Gaming",
  behance: "Creative",
  dribbble: "Creative",
  deviantart: "Creative",
  appleMusic: "Music",
  audiomack: "Music",
  beatstars: "Music",
  bandcamp: "Music",
  tidal: "Music",
  onlyfans: "Social",
  github: "Creative",
  productHunt: "Creative",
  googlePlay: "Gaming",
  appStore: "Gaming",
  other: "Other",
};
