export const permissionCatalog = [
  {
    key: "admin.access",
    name: "Truy cập quản trị",
    description: "Cho phép truy cập khu vực admin.",
    group: "system",
  },
  {
    key: "users.read",
    name: "Xem người dùng",
    description: "Xem danh sách và chi tiết người dùng.",
    group: "users",
  },
  {
    key: "users.create",
    name: "Tạo người dùng",
    description: "Tạo tài khoản từ trang quản trị.",
    group: "users",
  },
  {
    key: "users.update",
    name: "Sửa người dùng",
    description: "Cập nhật tài khoản và phân quyền người dùng.",
    group: "users",
  },
  {
    key: "users.delete",
    name: "Xóa người dùng",
    description: "Xóa tài khoản không còn dữ liệu liên quan.",
    group: "users",
  },
  {
    key: "users.manage-status",
    name: "Quản lý trạng thái người dùng",
    description: "Kích hoạt, vô hiệu hóa, khóa hoặc tạm ngưng tài khoản.",
    group: "users",
  },
  {
    key: "users.manage-roles",
    name: "Quản lý quyền người dùng",
    description: "Gán role và permission trực tiếp cho người dùng.",
    group: "users",
  },
  {
    key: "users.verify-email",
    name: "Xác minh email người dùng",
    description: "Cho phép quản trị viên xác minh email thủ công.",
    group: "users",
  },
  {
    key: "users.revoke-sessions",
    name: "Thu hồi phiên người dùng",
    description: "Đăng xuất người dùng khỏi tất cả thiết bị.",
    group: "users",
  },
  {
    key: "links.read",
    name: "Xem social link",
    description: "Xem danh sách và chi tiết social link của hệ thống.",
    group: "social-links",
  },
  {
    key: "links.update",
    name: "Sửa social link",
    description:
      "Cập nhật nội dung, trạng thái và khôi phục social link.",
    group: "social-links",
  },
  {
    key: "links.delete",
    name: "Xóa social link",
    description: "Đưa social link vào thùng rác.",
    group: "social-links",
  },
  {
    key: "pages.read",
    name: "Xem trang nội dung",
    description: "Xem danh sách, chi tiết và bản xem trước trang nội dung.",
    group: "pages",
  },
  {
    key: "pages.create",
    name: "Tạo trang nội dung",
    description: "Tạo trang nội dung mới.",
    group: "pages",
  },
  {
    key: "pages.update",
    name: "Sửa trang nội dung",
    description: "Cập nhật nội dung, SEO và trạng thái trang.",
    group: "pages",
  },
  {
    key: "pages.delete",
    name: "Xóa trang nội dung",
    description: "Chuyển trang nội dung vào thùng rác.",
    group: "pages",
  },
  {
    key: "pages.publish",
    name: "Xuất bản trang nội dung",
    description: "Xuất bản một hoặc nhiều trang nội dung.",
    group: "pages",
  },
  {
    key: "menus.read",
    name: "Xem menu website",
    description: "Xem menu, vị trí hiển thị và bản nháp hiện tại.",
    group: "menus",
  },
  {
    key: "menus.create",
    name: "Tạo menu website",
    description: "Tạo menu điều hướng mới.",
    group: "menus",
  },
  {
    key: "menus.update",
    name: "Sửa menu website",
    description: "Cập nhật cấu trúc và bản dịch menu.",
    group: "menus",
  },
  {
    key: "menus.delete",
    name: "Xóa menu website",
    description: "Xóa menu chưa còn được gán vị trí.",
    group: "menus",
  },
  {
    key: "menus.publish",
    name: "Xuất bản menu website",
    description: "Xuất bản hoặc gỡ xuất bản snapshot menu.",
    group: "menus",
  },
  {
    key: "menus.assign",
    name: "Gán vị trí menu website",
    description: "Gán menu đã quản lý vào các vị trí công khai.",
    group: "menus",
  },
  {
    key: "monetization-levels.read",
    name: "Xem cấp độ kiếm tiền",
    description: "Xem danh sách và cấu hình cấp độ kiếm tiền.",
    group: "monetization",
  },
  {
    key: "monetization-levels.create",
    name: "Tạo cấp độ kiếm tiền",
    description: "Tạo cấp độ kiếm tiền mới.",
    group: "monetization",
  },
  {
    key: "monetization-levels.update",
    name: "Sửa cấp độ kiếm tiền",
    description: "Cập nhật route, rate và trải nghiệm quảng cáo.",
    group: "monetization",
  },
  {
    key: "monetization-levels.delete",
    name: "Xóa cấp độ kiếm tiền",
    description: "Xóa cấp độ kiếm tiền chưa được sử dụng.",
    group: "monetization",
  },
  {
    key: "payment-methods.read",
    name: "Xem phương thức thanh toán",
    description: "Xem danh mục phương thức nhận thanh toán.",
    group: "payments",
  },
  {
    key: "payment-methods.create",
    name: "Tạo phương thức thanh toán",
    description: "Tạo phương thức nhận thanh toán mới.",
    group: "payments",
  },
  {
    key: "payment-methods.update",
    name: "Sửa phương thức thanh toán",
    description: "Cập nhật phí, hạn mức và trường thông tin thanh toán.",
    group: "payments",
  },
  {
    key: "payment-methods.delete",
    name: "Xóa phương thức thanh toán",
    description: "Xóa phương thức thanh toán chưa được thành viên sử dụng.",
    group: "payments",
  },
  {
    key: "withdrawals.read",
    name: "Xem yêu cầu rút tiền",
    description: "Xem danh sách và chi tiết yêu cầu rút tiền.",
    group: "payments",
  },
  {
    key: "withdrawals.process",
    name: "Xử lý yêu cầu rút tiền",
    description: "Tiếp nhận, hoàn tất hoặc từ chối yêu cầu rút tiền.",
    group: "payments",
  },
  {
    key: "support.read",
    name: "Xem ticket hỗ trợ",
    description: "Xem danh sách và nội dung ticket hỗ trợ của thành viên.",
    group: "support",
  },
  {
    key: "support.reply",
    name: "Phản hồi ticket hỗ trợ",
    description: "Gửi phản hồi tới thành viên trong ticket hỗ trợ.",
    group: "support",
  },
  {
    key: "support.manage",
    name: "Quản lý ticket hỗ trợ",
    description: "Gán người xử lý, độ ưu tiên và trạng thái ticket.",
    group: "support",
  },
  {
    key: "languages.read",
    name: "Xem ngôn ngữ",
    description: "Xem danh mục ngôn ngữ của hệ thống.",
    group: "localization",
  },
  {
    key: "languages.create",
    name: "Tạo ngôn ngữ",
    description: "Thêm locale nội dung mới.",
    group: "localization",
  },
  {
    key: "languages.update",
    name: "Sửa ngôn ngữ",
    description: "Cập nhật trạng thái, mặc định và thứ tự ngôn ngữ.",
    group: "localization",
  },
  {
    key: "languages.delete",
    name: "Xóa ngôn ngữ",
    description: "Xóa ngôn ngữ chưa có nội dung liên quan.",
    group: "localization",
  },
  {
    key: "settings.read",
    name: "Xem cài đặt website",
    description: "Xem thông tin, nhận diện và liên hệ của website.",
    group: "settings",
  },
  {
    key: "settings.update",
    name: "Sửa cài đặt website",
    description: "Cập nhật thông tin, nhận diện và liên hệ của website.",
    group: "settings",
  },
  {
    key: "currencies.read",
    name: "Xem cấu hình tiền tệ",
    description: "Xem danh mục tiền tệ và tỷ giá quy đổi của website.",
    group: "settings",
  },
  {
    key: "currencies.create",
    name: "Tạo tiền tệ",
    description: "Thêm tiền tệ hiển thị mới cho website.",
    group: "settings",
  },
  {
    key: "currencies.update",
    name: "Sửa tiền tệ",
    description: "Cập nhật tỷ giá, trạng thái và tiền tệ mặc định.",
    group: "settings",
  },
  {
    key: "currencies.delete",
    name: "Xóa tiền tệ",
    description: "Xóa tiền tệ chưa còn được người dùng lựa chọn.",
    group: "settings",
  },
  {
    key: "admin-media.read",
    name: "Xem thư viện Media Admin",
    description: "Xem file và thư mục thuộc thư viện Media Admin.",
    group: "admin-media",
  },
  {
    key: "admin-media.upload",
    name: "Tải Media Admin",
    description: "Tải ảnh mới lên thư viện Media Admin.",
    group: "admin-media",
  },
  {
    key: "admin-media.update",
    name: "Sửa Media Admin",
    description: "Cập nhật metadata và vị trí file Media Admin.",
    group: "admin-media",
  },
  {
    key: "admin-media.delete",
    name: "Xóa Media Admin",
    description: "Xóa file không còn được sử dụng khỏi Media Admin.",
    group: "admin-media",
  },
  {
    key: "admin-media.manage-folders",
    name: "Quản lý thư mục Media Admin",
    description: "Tạo, đổi tên, di chuyển và xóa thư mục Media Admin.",
    group: "admin-media",
  },
  {
    key: "roles.read",
    name: "Xem phân quyền",
    description: "Xem role và permission.",
    group: "authorization",
  },
  {
    key: "roles.create",
    name: "Tạo role",
    description: "Tạo role tùy chỉnh.",
    group: "authorization",
  },
  {
    key: "roles.update",
    name: "Sửa role",
    description: "Cập nhật role và permission của role.",
    group: "authorization",
  },
  {
    key: "roles.delete",
    name: "Xóa role",
    description: "Xóa role tùy chỉnh chưa được sử dụng.",
    group: "authorization",
  },
] as const;

export type PermissionDefinition = (typeof permissionCatalog)[number];
export type PermissionKey = PermissionDefinition["key"];
