"use client";

import { AlertTriangle, ArrowLeft, Bot, CircleDollarSign, Globe2, Link2, Network, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import * as React from "react";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";

import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import type { AdminAccessLogsResponse, UserAccessAnalysis } from "../types";
import { formatMoney } from "./access-logs-table-columns";

const chartConfig = { requestCount: { label: "Request", color: "var(--primary)" } } satisfies ChartConfig;

export function UserAccessAnalysisView({ analysis, logs, range }: { analysis: UserAccessAnalysis; logs: AdminAccessLogsResponse; range: string }) {
  const router = useRouter();
  const [from, setFrom] = React.useState(toLocal(analysis.period.from));
  const [to, setTo] = React.useState(toLocal(analysis.period.to));
  const riskLabels = { low: "Low", medium: "Medium", high: "High", critical: "Critical" };

  function chooseRange(value: string) { router.push(`/admin/users/${analysis.user.id}/access-analysis?range=${value}`); }
  function applyCustom() { router.push(`/admin/users/${analysis.user.id}/access-analysis?range=custom&from=${encodeURIComponent(new Date(from).toISOString())}&to=${encodeURIComponent(new Date(to).toISOString())}`); }

  return <div className="mx-auto flex w-full max-w-[1500px] flex-col gap-6">
    <Button variant="ghost" size="sm" className="-ml-3 w-fit" asChild><Link href={`/admin/users/${analysis.user.id}`}><ArrowLeft /> Quay lại user</Link></Button>
    <AdminPageHeader title={`Phân tích traffic · ${analysis.user.name}`} description={`${analysis.user.email} · Risk score chỉ được tính trong response hiện tại.`} breadcrumbs={[{label:"Dashboard",href:"/admin"},{label:"Users",href:"/admin/users"},{label:analysis.user.name,href:`/admin/users/${analysis.user.id}`},{label:"Access analysis"}]} actions={<Button variant="outline" asChild><Link href={`/admin/stu-access-logs?userId=${analysis.user.id}`}><Network /> Mở Access Logs</Link></Button>} />

    <Card><CardContent className="flex flex-col gap-4 p-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-wrap gap-2">{[["24h","24 giờ"],["7d","7 ngày"],["30d","30 ngày"]].map(([value,label]) => <Button key={value} variant={range === value ? "default" : "outline"} onClick={() => chooseRange(value)}>{label}</Button>)}</div><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><div className="space-y-1"><Label>Từ</Label><Input type="datetime-local" value={from} onChange={(event) => setFrom(event.target.value)} /></div><div className="space-y-1"><Label>Đến</Label><Input type="datetime-local" value={to} onChange={(event) => setTo(event.target.value)} /></div><Button variant={range === "custom" ? "default" : "outline"} onClick={applyCustom}>Áp dụng</Button></div></CardContent></Card>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Tổng request" value={analysis.summary.totalRequests} icon={Network}/><Summary label="Được tính revenue" value={analysis.summary.earnedRequests} icon={ShieldCheck}/><Summary label="Bị từ chối" value={analysis.summary.rejectedRequests} icon={AlertTriangle}/><Summary label="Tổng revenue" value={formatMoney(analysis.summary.totalRevenue)} icon={CircleDollarSign}/><Summary label="IP duy nhất" value={analysis.summary.uniqueIps} icon={Network}/><Summary label="Agent duy nhất" value={analysis.summary.uniqueAgents} icon={Bot}/><Summary label="Quốc gia" value={analysis.summary.uniqueCountries} icon={Globe2}/><Summary label="Link" value={analysis.summary.uniqueLinks} icon={Link2}/></section>

    <Card className="overflow-hidden"><CardContent className="grid gap-6 p-6 lg:grid-cols-[240px_1fr]"><div className="flex flex-col items-center justify-center rounded-xl border bg-muted/20 p-6 text-center"><p className="text-sm text-muted-foreground">Risk score</p><p className="mt-2 text-6xl font-bold tabular-nums">{analysis.risk.score}</p><Badge className="mt-3" variant={analysis.risk.level === "high" || analysis.risk.level === "critical" ? "destructive" : "outline"}>{riskLabels[analysis.risk.level]}</Badge><p className="mt-3 text-xs text-muted-foreground">{analysis.risk.triggeredRuleCount} rule kích hoạt</p></div><div><h2 className="font-semibold">Lý do và evidence</h2><div className="mt-3 space-y-3">{analysis.reasons.length ? analysis.reasons.map((reason) => <div key={reason.code} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><Badge variant="outline">{reason.code}</Badge><strong className="text-destructive">+{reason.score}</strong></div><p className="mt-2 text-sm">{reason.message}</p>{reason.evidence ? <pre className="mt-3 overflow-x-auto rounded-lg bg-muted p-3 text-xs">{JSON.stringify(reason.evidence,null,2)}</pre> : null}</div>) : <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">Không có rule nào kích hoạt trong phạm vi này.</p>}</div></div></CardContent></Card>

    <Tabs defaultValue="analysis"><TabsList><TabsTrigger value="analysis">Phân tích</TabsTrigger><TabsTrigger value="logs">Access logs ({logs.total})</TabsTrigger></TabsList><TabsContent value="analysis" className="space-y-6"><Card><CardHeader><CardTitle>Traffic timeline</CardTitle><CardDescription>So sánh theo giờ hoặc ngày tùy phạm vi.</CardDescription></CardHeader><CardContent><ChartContainer config={chartConfig} className="h-72 w-full"><AreaChart data={analysis.trafficTimeline}><CartesianGrid vertical={false}/><XAxis dataKey="bucket" tickFormatter={(value) => new Date(value).toLocaleDateString("vi-VN", { day:"2-digit", month:"2-digit", hour:"2-digit" })} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent />} /><Area dataKey="requestCount" type="monotone" stroke="var(--color-requestCount)" fill="var(--color-requestCount)" fillOpacity={0.15}/></AreaChart></ChartContainer></CardContent></Card><div className="grid gap-6 xl:grid-cols-2"><AnalysisTable title="Top IP" headers={["IP","Request","Revenue"]} rows={analysis.topIps.map((item) => [item.ipAddress || "—",item.requestCount,formatMoney(item.revenue)])}/><AnalysisTable title="Top link" headers={["Link","Request","IP"]} rows={analysis.topLinks.map((item) => [item.title,item.requestCount,item.distinctIpCount])}/><AnalysisTable title="Top agent (tín hiệu yếu)" headers={["Agent hash","Request","Owner"]} rows={analysis.topAgents.map((item) => [item.agentHash.slice(0,12),item.requestCount,item.distinctUserCount])}/><AnalysisTable title="Phân bố quốc gia" headers={["Country","Request","Revenue"]} rows={analysis.countryDistribution.map((item) => [item.country,item.requestCount,formatMoney(item.revenue)])}/></div></TabsContent><TabsContent value="logs"><RawLogs logs={logs} userId={analysis.user.id} range={range} period={analysis.period} /></TabsContent></Tabs>
  </div>;
}

function Summary({ label, value, icon: Icon }: { label: string; value: React.ReactNode; icon: typeof Network }) { return <Card><CardContent className="p-5"><p className="flex items-center justify-between gap-2 text-sm text-muted-foreground">{label}<Icon className="size-4" /></p><p className="mt-3 text-2xl font-semibold tabular-nums">{typeof value === "number" ? new Intl.NumberFormat("vi-VN").format(value) : value}</p></CardContent></Card>; }
function AnalysisTable({ title, headers, rows }: { title: string; headers: string[]; rows: React.ReactNode[][] }) { return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow>{headers.map((item) => <TableHead key={item}>{item}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.length ? rows.slice(0,10).map((row,index) => <TableRow key={index}>{row.map((cell,cellIndex) => <TableCell key={cellIndex} className={cellIndex ? "tabular-nums" : "max-w-52 truncate"}>{cell}</TableCell>)}</TableRow>) : <TableRow><TableCell colSpan={headers.length} className="text-center text-muted-foreground">Chưa có dữ liệu.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>; }
function RawLogs({ logs, userId, range, period }: { logs: AdminAccessLogsResponse; userId: number; range: string; period: { from: string; to: string } }) { const router = useRouter(); const custom = range === "custom" ? `&from=${encodeURIComponent(period.from)}&to=${encodeURIComponent(period.to)}` : ""; return <Card><CardHeader><CardTitle>Raw access logs</CardTitle><CardDescription>Phân trang độc lập; không nằm trong response phân tích.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Thời gian</TableHead><TableHead>Link</TableHead><TableHead>IP</TableHead><TableHead>Country</TableHead><TableHead>Revenue</TableHead><TableHead>Trạng thái</TableHead></TableRow></TableHeader><TableBody>{logs.items.map((log) => <TableRow key={log.id}><TableCell className="whitespace-nowrap">{new Date(log.createdAt).toLocaleString("vi-VN")}</TableCell><TableCell>{log.link.title}</TableCell><TableCell className="font-mono text-xs">{log.ipAddress || "—"}</TableCell><TableCell>{log.country}</TableCell><TableCell>{formatMoney(log.revenue)}</TableCell><TableCell>{log.detectionStatus}</TableCell></TableRow>)}</TableBody></Table></div><div className="mt-4 flex items-center justify-between"><p className="text-sm text-muted-foreground">Trang {logs.page}/{logs.pageCount}</p><div className="flex gap-2"><Button variant="outline" disabled={logs.page <= 1} onClick={() => router.push(`/admin/users/${userId}/access-analysis?range=${range}${custom}&logPage=${logs.page - 1}`)}>Trước</Button><Button variant="outline" disabled={logs.page >= logs.pageCount} onClick={() => router.push(`/admin/users/${userId}/access-analysis?range=${range}${custom}&logPage=${logs.page + 1}`)}>Sau</Button></div></div></CardContent></Card>; }
function toLocal(value: string) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0,16); }
